---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# cmor.tools

<!-- badges: start -->
<!-- badges: end -->

The goal of the `projecttools` ecosystem is to provide standardised tools to
initialise a research project folder, undertake analysis, and generate output
reports (journal manuscripts, etc.) for research projects undertaken at CMOR.
This package installs and loads all packages in the ecosystem.

## Installation

You can install **`projecttools`** from [GitHub](https://github.com) with:

``` r
#install.packages("pak")
pak::pak("rosswilson-nz/projecttools")
```

## Packages

`library(projecttools)` will load the `projecttools` packages:

-   [`formattr`](https://github.com/rosswilson-nz/formattr): Format numbers &
    descriptive statistics nicely for output reports;
-   [`projectsetup`](https://github.com/rosswilson-nz/projectsetup): Data
    analysis project workflow setup tools;
-   [`pipelinetools`](https://github.com/rosswilson-nz/pipelinetools): Functions
    used in setting up [targets](https://github.com/ropensci/targets) pipelines.
-   [`plottools`](https://github.com/rosswilson-nz/plottools):
    [ggplot2](https://github.com/tidyverse/ggplot2) themes and colour palettes
    for figure formatting, and additional geoms;
-   [`ttables`](https://github.com/rosswilson-nz/ttables): Create tables in
    Typst format for inclusion in output documents.
